# Import a Keras model into IBM Watson Machine Learning

Importing a model into Watson Machine Learning means to store a trained model in your Watson Machine Learning repository and then deploy the stored model.  This notebook demonstrates importing a Keras model.

See also: <a href="https://dataplatform.cloud.ibm.com/docs/content/analyze-data/ml-import-keras.html" target="_blank" rel="noopener noreferrer">Importing a Keras model</a>

This notebook runs on Python 3.5.


### Notebook sections

[Step 0: Build, train, and save a model](#step0)

[Step 1: Store the model in your Watson Machine Learning repository](#step1)

[Step 2: Deploy the stored modelin your Watson Machine Learning service](#step2)

## <a id="step0"></a> Step 0: Build, train, and save a model

**About the sample model**

The sample model built here classifies text messages from fictional customers into two categories:
- "social" : The message might just be social and friendly, or the message lacks enough text to perform in-depth analysis
- "problem or question" : The message describes a prob1em or asks a questions

Classifying messages this way is useful for multiple purposes:
- Automating responses (eg. respond to social messages with a generial greeting, prompting the user to type their question or problem if they have one)
- Cleaning out social message for post-hoc analysis

The data used to train the model is the "sample-customer-messages.csv" training data in the IBM Watson Studio community: <a href="https://dataplatform.cloud.ibm.com/exchange/public/entry/view/015ddef6a868441188268a123404f744" target="_blank" rel="noopener noreferrer">Customer messages sample data</a>.

### Get and prepare training data

In [1]:
!pip install wget # Needed to download sample training data

You are using pip version 9.0.1, however version 19.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


In [2]:
# Download sample training data to the notebook working directory
import wget
training_data_url = 'https://dataplatform.cloud.ibm.com/data/exchange-api/v1/entries/015ddef6a868441188268a123404f744/data?accessKey=c8d0403d844a82df9ecd264df02f2b07'
filename = wget.download( training_data_url )
print( filename )

sample-customer-messages (2).csv


In [3]:
# Read sample data into Pandas DataFrame
import pandas as pd
df = pd.read_csv( filename, names=[ "message", "class_name" ] )
df[6:9]

message class_name
6                                       Greetings :)         hi
7  hai how can i do analyze with csv file is ther...   question
8                    Having issues setup WML service    problem

In [4]:
# Split the data into training and test sets
# https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html
from sklearn.model_selection import train_test_split
train, test = train_test_split( df, test_size = 0.1 )
test

message class_name
4    Good morning can you help me upload a shapefile?   question
73  Hi there Im having trouble using my CSV data f...    problem
58  Hi I would like to signup for a trail but I am...    problem
99  When I try to add a model to any project I get...    problem
47  Hi I am trying to request a new API token but ...    problem
87  I deployed my WatsonML model and have a Scorin...    problem
6                                        Greetings :)         hi
39                                  Hi  Anyone there?         hi
68      Hi team how can i import data into a project?   question
67                              Hi not able to signup    problem

In [5]:
# Convert words to numbers
# https://keras.io/preprocessing/text/#tokenizer
from keras.preprocessing.text import Tokenizer
t = Tokenizer()
t.fit_on_texts( train["message"] )
X_train = t.texts_to_sequences( train["message"] )
X_test  = t.texts_to_sequences( test["message"] )
X_test[0:4]

/Users/jinsalex/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


[[38, 77, 9, 11, 17, 27, 45, 4],
 [3, 24, 18, 31, 70, 58, 7, 32, 19, 103, 7, 43, 61, 42],
 [3, 2, 261, 164, 1, 103, 4, 47, 2, 33, 40, 29, 15],
 [21, 2, 230, 1, 76, 4, 42, 1, 48, 28, 2, 39, 29, 15]]

In [6]:
# Pad the shorter entries
# https://keras.io/preprocessing/sequence/#pad_sequences
from keras.preprocessing.sequence import pad_sequences
max_len = max( len(x) for x in X_train )
X_train = pad_sequences( X_train, padding='post', maxlen=max_len )
X_test  = pad_sequences( X_test,  padding='post', maxlen=max_len )
X_test[0]

array([38, 77,  9, 11, 17, 27, 45,  4,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0], dtype=int32)

In [7]:
# Convert the labels to binary labels
import scipy
import numpy as np
y_train = np.array( [ [ 1, 0 ] if class_name == "hi" else [ 0, 1 ] for class_name in train[ "class_name" ] ] )
y_test  = np.array( [ [ 1, 0 ] if class_name == "hi" else [ 0, 1 ] for class_name in test[ "class_name" ] ] )
y_test

array([[0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [1, 0],
       [1, 0],
       [0, 1],
       [0, 1]])

### Build a neural network

In [8]:
# Create a simple sequential model
# https://keras.io/models/sequential

from keras.models import Sequential
from keras import layers

vocab_size    = len( t.word_counts ) + 1
embedding_dim = 50
num_classes   = 2

model = Sequential()
model.add( layers.Embedding( input_dim    = vocab_size,        # https://keras.io/layers/embeddings
                             output_dim   = embedding_dim, 
                             input_length = max_len,
                             trainable    = True ) )
model.add( layers.Flatten() )                                  # https://keras.io/layers/core/#flatten
model.add( layers.Dense( num_classes, activation='sigmoid' ) ) # https://keras.io/layers/core/#dense
model.add( layers.Activation( "softmax" ) )                    # https://en.wikipedia.org/wiki/Softmax_function

model.compile( optimizer = "adam",                # https://www.dlology.com/blog/quick-notes-on-how-to-choose-optimizer-in-keras
               loss      = "binary_crossentropy", # https://www.dlology.com/blog/how-to-choose-last-layer-activation-and-loss-function
               metrics   = [ "accuracy" ] )

### Train and evaluate model

In [9]:
num_epochs = 15

history = model.fit( X_train, y_train,
                     batch_size = 10,
                     epochs     = num_epochs,
                     verbose    = False,
                     validation_split = 0.1 )

In [10]:
import matplotlib.pyplot as plt
plt.style.use( "seaborn-white" )

plt.title(  "Accuracy", fontsize = 18)

x = range( 1, num_epochs + 1 )
plt.plot( x, history.history[ "acc" ],     label = "Training"   )
plt.plot( x, history.history[ "val_acc" ], label = "Validation" )

legend = plt.legend( loc="upper left" )

In [11]:
test

message class_name
4    Good morning can you help me upload a shapefile?   question
73  Hi there Im having trouble using my CSV data f...    problem
58  Hi I would like to signup for a trail but I am...    problem
99  When I try to add a model to any project I get...    problem
47  Hi I am trying to request a new API token but ...    problem
87  I deployed my WatsonML model and have a Scorin...    problem
6                                        Greetings :)         hi
39                                  Hi  Anyone there?         hi
68      Hi team how can i import data into a project?   question
67                              Hi not able to signup    problem

In [12]:
test_results = model.predict_classes( X_test )
print( test_results )

[1 1 1 1 1 1 0 0 1 0]


### Save the model in a .tgz file

In [13]:
# https://keras.io/getting-started/faq/#how-can-i-save-a-keras-model
model.save( "message-classification-model.h5" )

In [14]:
!tar -zcvf message-classification-model.tgz message-classification-model.h5

a message-classification-model.h5


In [15]:
!ls -l

total 1072
-rw-r--r--  1 jinsalex  staff   51758 Jun 11 15:59 keras-import-python.ipynb
-rw-r--r--  1 jinsalex  staff  227928 Jun 11 16:00 message-classification-model.h5
-rw-r--r--  1 jinsalex  staff  189256 Jun 11 16:00 message-classification-model.tgz
-rw-r--r--  1 jinsalex  staff    5781 Jun 11 15:56 sample-customer-messages (1).csv
-rw-r--r--  1 jinsalex  staff    5781 Jun 11 16:00 sample-customer-messages (2).csv
-rw-r--r--  1 jinsalex  staff    5781 Jun 11 15:52 sample-customer-messages.csv


## <a id="step1"></a> Step 1: Store the model in your Watson Machine Learning repository

This section of the notebook demonstrates calling the <a href="https://wml-api-pyclient.mybluemix.net/index.html?highlight=store_model#client.Repository.store_model" target="_blank" rel="noopener noreferrer">store_model</a> function

Paste your Watson Machine Learning credentials in the following cell.

See: <a href="https://dataplatform.cloud.ibm.com/docs/content/analyze-data/ml-get-wml-credentials.html" target="_blank" rel="noopener noreferrer">Looking up credentials</a>

In [16]:
# Create a Watson Machine Learning client instance
from watson_machine_learning_client import WatsonMachineLearningAPIClient
wml_credentials = {
    "apikey"    : "value",
    "instance_id" : "instance_id",
    "url"    : "url"
}
client = WatsonMachineLearningAPIClient( wml_credentials )

/Users/jinsalex/anaconda3/lib/python3.6/site-packages/sklearn/externals/joblib/__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=DeprecationWarning)


!pip show keras
!pip install keras==2.1.3

In [17]:
metadata = {
    client.repository.ModelMetaNames.NAME: "keras model",
    client.repository.ModelMetaNames.FRAMEWORK_NAME: "tensorflow",
    client.repository.ModelMetaNames.FRAMEWORK_VERSION: "1.5",
    client.repository.ModelMetaNames.FRAMEWORK_LIBRARIES: [{'name':'keras', 'version': '2.1.3'}]}
model_details = client.repository.store_model( model="message-classification-model.tgz", meta_props=metadata )

## <a id="step2"></a> Step 2: Deploy the stored the model in your Watson Machine Learning service

This section of the notebook demonstrates calling the <a href="https://wml-api-pyclient.mybluemix.net/index.html?highlight=deploy#client.Deployments.create" target="_blank" rel="noopener noreferrer">deployments.create</a> function

In [18]:
# Deploy the stored model as an online web service deployment
model_id = model_details["metadata"]["guid"]
deployment_details = client.deployments.create( artifact_uid=model_id, name="Keras deployment" )



#######################################################################################

Synchronous deployment creation for uid: 'd55734d6-5945-451f-874c-3b91324233df' started

#######################################################################################


INITIALIZING
DEPLOY_SUCCESS


------------------------------------------------------------------------------------------------
Successfully finished deployment creation, deployment_uid='ffb027ba-bb19-4842-a527-95f274fa97d0'
------------------------------------------------------------------------------------------------




In [19]:
# Test the deployment
model_endpoint_url = client.deployments.get_scoring_url( deployment_details )
payload = { "values" : X_test.tolist() }
client.deployments.score( model_endpoint_url, payload )

{'fields': ['prediction', 'prediction_classes', 'probability'],
 'values': [[[0.3985484540462494, 0.6014516353607178],
   1,
   [0.3985484540462494, 0.6014516353607178]],
  [[0.27617669105529785, 0.7238233685493469],
   1,
   [0.27617669105529785, 0.7238233685493469]],
  [[0.274316668510437, 0.7256833910942078],
   1,
   [0.274316668510437, 0.7256833910942078]],
  [[0.27395668625831604, 0.7260433435440063],
   1,
   [0.27395668625831604, 0.7260433435440063]],
  [[0.27482694387435913, 0.7251730561256409],
   1,
   [0.27482694387435913, 0.7251730561256409]],
  [[0.29424726963043213, 0.7057527303695679],
   1,
   [0.29424726963043213, 0.7057527303695679]],
  [[0.7057399153709412, 0.2942601144313812],
   0,
   [0.7057399153709412, 0.2942601144313812]],
  [[0.6847215890884399, 0.3152783513069153],
   0,
   [0.6847215890884399, 0.3152783513069153]],
  [[0.281570702791214, 0.7184292674064636],
   1,
   [0.281570702791214, 0.7184292674064636]],
  [[0.5620117783546448, 0.43798819184303284],
   

## Summary
In this notebook, you imported a Keras model into Watson Machine Learning using the Watson Machine Learning Python client.

### <a id="authors"></a>Authors

**Sarah Packowski** is a member of the IBM Watson Studio Content Design team in Canada.


<hr>
Copyright &copy; IBM Corp. 2019. This notebook and its source code are released under the terms of the MIT License.

<div style="background:#F5F7FA; height:110px; padding: 2em; font-size:14px;">
<span style="font-size:18px;color:#152935;">Love this notebook? </span>
<span style="font-size:15px;color:#152935;float:right;margin-right:40px;">Don't have an account yet?</span><br>
<span style="color:#5A6872;">Share it with your colleagues and help them discover the power of Watson Studio!</span>
<span style="border: 1px solid #3d70b2;padding:8px;float:right;margin-right:40px; color:#3d70b2;"><a href="https://ibm.co/wsnotebooks" target="_blank" style="color: #3d70b2;text-decoration: none;">Sign Up</a></span><br>
</div>